[package]
name = "canvas"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
image = "0.25.5"
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "sqlite"] } # sqlite
tokio = { version = "1", features = ["macros", "rt-multi-thread"] } # network stuff